### ISSUE TITLE
There are RT issues

### ISSUE THREAD

**Issue by eserte** [sekimura/lwp-useragent-withcache#3]
Please see https://rt.cpan.org/Public/Bug/Display.html?id=94510 (with patch!).

**Comment by sekimura** [comment]
patches as a github pull-request would be appreciated. Thanks!

**Comment by eserte** [comment]
See https://github.com/sekimura/lwp-useragent-withcache/pull/4

**Comment by sekimura** [comment]
thanks for submitting PR. I've uploaded 0.13 to pause.cpan.org.

https://metacpan.org/release/SEKIMURA/LWP-UserAgent-WithCache-0.13

Cheers! 🍺
